#!/bin/bash
STR="{
  \"libs\": [
    \"browser\",
    \"jquery\"
  ],
  \"loadEagerly\": [
    \"importantfile.js\"
  ],
  \"plugins\": {
    \"requirejs\": {
      \"baseURL\": \"./\",
      \"paths\": {}
    }
  }
}"

echo $STR > .tern-project
